### ISSUE TITLE
stream error: stream ID 1; PROTOCOL_ERROR;

### ISSUE THREAD

**Issue by White2001Offl** [Danny-Dasilva/CycleTLS#114]
### Description

Getting this error `\nGet "https://host.com/": stream error: stream ID 1; PROTOCOL_ERROR; server not authoritative for push with host "host.com"`

Its weird that as its happening only in some sites and only with proxy.
not sure if its site / proxy / tls issue

I can send you the site link if you want via mail so you can test it

### Issue Type

Bug

### Operating System

Windows 10, Mac OS

### Node Version

Node 16.x

### Golang Version

Go 14.x

### Relevant Log Output

```shell
\nGet "https://host.com/": stream error: stream ID 1; PROTOCOL_ERROR; server not authoritative for push with host "host.com"
```

**Comment by White2001Offl** [comment]
* Golang 1.16 btw

**Comment by KawaCode** [comment]
@White2001Offl It is only for HTTP2, no for HTTP1.

**Comment by Danny-Dasilva** [comment]
If you could give me an example site that can reproduce this error that would be very helpful.

**Comment by Danny-Dasilva** [comment]
@White2001Offl this issue should be fixed, send you an email with example code.

Closing this issue for now but feel free to reopen if anyone encounters the issue again.

**Comment by RTCommerce** [comment]
@Danny-Dasilva - would you be able to send me the details of the fix?  I'm working off a fork of this and would like to try and incorporate it if possible.  Things were working fine for the last few months but I started seeing a ton of these today.

**Comment by Kimmlouis** [comment]
Still getting an issue on a particular website please message me so i could show you the details, website and code . This is the exact error i am receiving . stream error: stream ID 1; INTERNAL_ERROR @Danny-Dasilva
